### ISSUE TITLE
Model Predictions

### ISSUE THREAD

**Issue by kiran-collab** [wingman-jr-addon/model#3]
Respected Sir
I have another query.
The logo/icon on the blocked image that is displayed with prediction is performed using which icon and could please forward me to the code in the repo to that.

**Comment by wingman-jr-addon** [comment]
I am going to close this because this is not something related to using the model.

Here is the code you are looking for: https://github.com/wingman-jr-addon/wingman_jr/blob/02dfd53325feec6b6f08fdbe93a2e411509673ec/processor.js#L203
